[build]
command = "npm install --legacy-peer-deps && NODE_ENV=production nx build host --configuration=production"
publish = "dist/apps/angular/host"
functions = "netlify/functions"

[build.environment]
NODE_ENV = "production"
NX_PRODUCTION = "true"
NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
from = "/module-federation.manifest.json"
to = "/module-federation.manifest.json"
status = 200

[[redirects]]
from = "/remoteEntry.mjs"
to = "/remoteEntry.mjs"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/*.(js|mjs)"
[headers.values]
Content-Type = "application/javascript"

[[headers]]
for = "/*.json"
[headers.values]
Content-Type = "application/json"
Access-Control-Allow-Origin = "*"
